(ns q9-oracle
  "The Clojure side of the whole-component acceptance: run `airtable.main` under
   nbb and print the same numbers the aarch64 artifact prints.

     nbb --classpath src:<kotoba-lang/text>/src q9-oracle.cljs

   GENERATED by scripts/gen-parity-harness.cljs. Only the layers that are
   derivable from the oracle without a judgement call are here: the route
   count, and as-int / as-bool / page-limit over the shared fixture table.
   The store, filter, pagination, handler and expand layers need fixtures
   shaped to this repository's entities and are NOT generated -- an arm that
   runs without asserting anything about this repository is worse than an
   absent one.

   ## The control

   `as-int` of \"12abc\" MUST differ between this harness and the artifact.
   The oracle's as-int is a reader conditional whose branches disagree: the
   :cljs branch is js/parseInt and yields 12, the :clj branch is
   Long/parseLong which throws and yields 0, and the component matches :clj.
   Measured across the cohort and recorded in kotoba-lang
   lang/q9-wave1-tranche-1.edn.

   So a run of this harness under nbb in which EVERYTHING matches has not
   demonstrated that it can detect a mismatch, and is not a pass. A run on a
   JVM would legitimately agree on that row; say which runtime produced any
   result."
  (:require [airtable.main :as m]
            [clojure.string :as str]))

;; Byte-identical in every hand-written harness in this cohort.
(def fixture-text
  {0 "12" 1 " 42 " 2 "-7" 3 "12abc" 4 "" 5 "true" 6 "TRUE" 7 "Yes" 8 "on"
   9 "1" 10 "0" 11 "false" 12 "null" 13 "nope"})

;; The same rolling hash the .kotoba computes: acc*131 + code point, mod
;; 1000000007, seeded 7. Every intermediate stays under 2^53, so a JS double
;; holds it exactly.
(defn str-hash [x]
  (reduce (fn [acc ch] (mod (+ (* acc 131) (.charCodeAt ch 0)) 1000000007)) 7 (seq (str x))))

;; The entity table, rendered the way `oracle-table` renders it. Unlike the
;; layers above, this one is DERIVED FROM THIS REPOSITORY'S OWN SPEC TABLE on
;; both sides, so it is the first row here that carries a per-repository
;; signal rather than a cohort-wide constant. It is also a runtime check for
;; the defect the component generator's evidence floor exists to catch: a
;; component whose tables still answer the TEMPLATE's prefixes passes
;; `amu check`, and fails here.
(defn coerce-csv [spec]
  (str/join "," (map (fn [[k v]] (str (name k) ":" (name v))) (:coerce spec))))

(defn table-line [spec]
  (str/join "|" [(:entity spec) (:plural spec) (:id-prefix spec)
                 (str/join "," (map name (:fields spec)))
                 (str/join "," (map name (:required spec)))
                 (coerce-csv spec)]))

(defn row [label v] (println (str label "\t" v)))

(println "; oracle = airtable.main under nbb")
(row "main(route-count)" (count m/routes))

(println "; as-int")
(doseq [i [0 1 2 3 4 12]] (row (str "as-int " i) (m/as-int (fixture-text i))))

(println "; as-bool")
(doseq [i [5 6 7 8 9 10 11 4 13]]
  (row (str "as-bool " i) (if (m/as-bool (fixture-text i)) 1 0)))

(println "; page-limit")
(doseq [r [-5 0 1 20 99 100 101 250]] (row (str "page-limit " r) (m/page-limit r)))

(println "; table")
(doseq [i (range (count m/entity-specs))]
  (row (str "table " i) (str-hash (table-line (nth m/entity-specs i)))))
